---
- name: Update system while excluding Docker packages
  hosts: all
  become: true
  tasks:
    - name: Update and upgrade packages excluding Docker
      ansible.builtin.apt:
        update_cache: yes
        upgrade: 'safe'
        name: '*'
        state: latest
        exclude: 'docker*,containerd*,docker-ce*'

