---
- name: Update system while excluding Docker packages
  hosts: all
  become: true
  tasks:
    - name: Hold Docker packages
      ansible.builtin.shell:
        cmd: dpkg --get-selections | grep -E '^(docker|containerd|docker-ce)' | sed s/install/hold/ | dpkg --set-selections

    - name: Update and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: 'safe'

    - name: Unhold Docker packages
      ansible.builtin.shell:
        cmd: dpkg --get-selections | grep -E '^(docker|containerd|docker-ce)' | sed s/hold/install/ | dpkg --set-selections
